title: Daily News Learning
baseurl: "/daily-news-learning"
url: "https://skyeminmin.github.io"
markdown: kramdown

# Build settings
plugins:
  - jekyll-feed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
