title: Daily News Learning
description: Learn English through daily news
baseurl: "/daily-news-learning"
url: "https://skyeminmin.github.io"

permalink: /:year/:month/:day/:title/
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
