title: Daily News Learning
description: Learn English through daily news reading
baseurl: "/daily-news-learning"
url: "https://skyeminmin.github.io"

markdown: kramdown
permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
