# Site settings
title: Daily News Learning Hub
description: A daily English news learning platform for middle school students
baseurl: "/daily-news-learning"
url: "https://skyeminmin.github.io"

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
