title: Daily News Learning Hub
description: Learn English through daily news
baseurl: "/daily-news-learning"
url: "https://skyeminmin.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
