title: Daily News Learning Hub
description: Learn English through daily news articles
baseurl: "/daily-news-learning"
url: "https://skyeminmin.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
