title: Daily News Learning Hub
description: Daily news articles for learning
baseurl: "/daily-news-learning"
url: "https://skyeminmin.github.io"

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
