title: Daily News Learning Hub
description: Learn English through daily news updates
baseurl: "/daily-news-learning"
url: "https://skyeminmin.github.io"

# Build settings
markdown: kramdown

# Remove theme setting as we're using custom layout
plugins:
  - jekyll-feed
