name: Update Daily News
on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz
          
      - name: Run update script
        run: |
          echo "Starting news update script..."
          python -u main.py  # -u 标志确保Python输出不被缓存
        continue-on-error: true  # 即使脚本失败也继续执行
      
      - name: Debug - Check news.json
        run: |
          echo "Checking news.json file..."
          if [ -f "data/news.json" ]; then
            echo "news.json exists. Content:"
            cat data/news.json
          else
            echo "ERROR: news.json does not exist!"
            echo "Current directory contents:"
            ls -la
            echo "Data directory contents (if exists):"
            ls -la data || echo "Data directory not found"
          fi
          
      - name: Commit and push if changed
        run: |
          echo "Configuring git..."
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          echo "Checking for changes..."
          git status
          
          echo "Adding news.json..."
          git add data/news.json
          
          echo "Committing changes if any..."
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update news data [skip ci]" && git push)
