name: Update News

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas json2html
    
    - name: Run update script
      env:
        GNEWS_API_KEY: dc6b340bb21432e40ed552ac70befd79
      run: |
        python config.py
    
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add news.json news.html news.csv
        git commit -m "Update news data" || echo "No changes to commit"
        git push
