name: Update News

on:
  schedule:
    - cron: '0 6 * * *'  # 每天早上6点运行
  push:
    branches: [ main ]   # 添加push触发
  workflow_dispatch:     # 允许手动触发

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml
        pip install nltk deep-translator
        
    - name: Check directory structure
      run: |
        mkdir -p data/study css js scripts
        ls -la
    
    - name: Run update script
      run: |
        python scripts/update_news.py
      continue-on-error: true
        
    - name: Process study content
      run: |
        python scripts/study_processor.py
      continue-on-error: true
    
    - name: Check for errors
      run: |
        if [ -f update_news.log ]; then
          echo "=== Update Log ==="
          cat update_news.log
          if grep -i "error" update_news.log; then
            echo "Errors found in the update process"
            exit 1
          fi
        fi
    
    - name: Validate news.json
      run: |
        if [ -f data/news.json ]; then
          python -c "import json; json.load(open('data/news.json'))"
          echo "news.json is valid JSON"
        else
          echo "news.json not found"
          exit 1
        fi
    
    - name: Debug Git status
      run: |
        echo "Git status:"
        git status
        echo "Git remote:"
        git remote -v
        echo "Current branch:"
        git branch --show-current
        echo "Git config:"
        git config --list
        
    - name: Configure Git
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    
    - name: Commit files
      run: |
        echo "Checking for changes..."
        git status
        git add -A
        git status
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto update news [skip ci]"
          echo "Changes committed"
        fi
    
    - name: Push changes
      run: |
        echo "Attempting to push changes..."
        git push origin HEAD || {
          echo "Push failed. Debugging information:"
          git remote -v
          git branch
          git status
          exit 1
        }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
