name: Update Daily News
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz
          
      - name: Run update script
        run: |
          echo "Starting news update script..."
          python -u main.py
        continue-on-error: true
      
      - name: Debug - Check news.json
        run: |
          echo "Checking news.json file..."
          if [ -f "data/news.json" ]; then
            echo "news.json exists. Content:"
            cat data/news.json
          else
            echo "ERROR: news.json does not exist!"
            echo "Current directory contents:"
            ls -la
            echo "Data directory contents (if exists):"
            ls -la data || echo "Data directory not found"
          fi
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/news.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update news data [skip ci]" && git push)
