name: Update News

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser pandas json2html requests
    
    - name: Run update script
      run: |
        python config.py
    
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update news data"
        file_pattern: 'news.*'
