name: Update News

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        check-latest: true
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests urllib3 pandas json2html
        python -m pip install GoogleNews
        pip install --upgrade requests
    
    - name: Run update script
      env:
        PYTHONWARNINGS: "ignore:Unverified HTTPS request"
        REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
        SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
      run: |
        python config.py
    
    - name: Check for changes
      id: git-check
      run: |
        git status --porcelain
        echo "modified=$(if git status --porcelain | grep .; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT
    
    - name: Commit and push if changed
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add -A
        timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
        git commit -m "Update news data: ${timestamp}"
        git push origin main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
